name: 'Header Check'
description: 'Check for the presence of specific HTTP response headers and their values'
icon: 'check-square'
inputs:
  endpoint:
    description: 'Endpoint to check for HTTP response headers'
    required: true
outputs:
  success:
    description: True or False value based on the finding of the expected header and its value
runs:
  using: 'node16'
  main: 'index.js'
